apiVersion: v1
kind: Service
metadata:
  name: bami-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: bami-nginx-search
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30006

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: bami-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bami-nginx-search
  template:
    metadata:
      labels:
        app: bami-nginx-search
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
